### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by courajs** [emberjs/list-view#102]
Have you guys thought about bower support for this? There's ember-list-view, but it's a shim by some guy which hasn't been updated in 4 months. Even just tagging versions occasionally would be a plus

**Comment by cfstras** [comment]
:+1: on this!

I can see the repo components/ember-list-view, but it seems to be empty... what gives?

**Comment by tim-evans** [comment]
The path going forward for this project is as an ember-cli addon. I agree that it would be nice to be able to use this as a bower addon.

For the meantime, let's put this on ice until list-view has moved to an addon.
