### ISSUE TITLE
Issues with itemController

### ISSUE THREAD

**Issue by ebryn** [emberjs/list-view#109]
Given this template:

```
{{#ember-list items=controller height=300 width=500 row-height=100 element-width=100}}
  {{superName}}
{{/ember-list}}
```

and these controller definitions:

```
App.ItemController = Ember.ObjectController.extend({
  superName: function() {
    return this.get('name') + '-super';
  }.property('name')
});

App.ApplicationController = Ember.ArrayController.extend({
  itemController: 'item'
});
```

As scrolling occurs, the item views lose their `style` attributes.

**Comment by tim-evans** [comment]
Controllers are going to be deprecated, so I don't see this as a big priority.

**Comment by bcleary6** [comment]
@stefanpenner it appears the latest build is throwing an exception when it is calling render().  buffer.dom is undefined which causes dom.createElement('div') to throw the exception.

Unless one of my dependent libraries is not on the correct version?

**Comment by stefanpenner** [comment]
@bcleary6 your comment appears to be unrelated to this specific issue. Please open a dedicated issue, with a concise example.

**Comment by stefanpenner** [comment]
ember is deprecating itemControllers, as such I have no plans on fixing these issues.
