### ISSUE TITLE
arrayDidChange implementation may cause un-needed re-render cascades.

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/list-view#13]

**Comment by Leooo** [comment]
The following condition is alwayts true?
'''if (start >= this._lastStartingIndex || start < this._lastEndingIndex) {

=> This should be "&&" instead of "||", more precisely:
```if ( (start+Math.max(addedCount,removedCount) >= this._lastStartingIndex) && start < this._lastEndingIndex) {

**Comment by Leooo** [comment]
I see another thing too, opening a new issue as I never know if closed issues are red.

**Comment by stefanpenner** [comment]
> if (start >= this._lastStartingIndex || start < this._lastEndingIndex) {

I believe this is to take into account optional elastic snap like in pull to refresh mode.

**Comment by Leooo** [comment]
Wow you lost me. The only thing that I noticed is that, whatever the value of `start`, if `this._lastStartingIndex < this._lastEndIndex`, then the above condition is true.

Moreover, at least in my case (content array built using a reduceComputed property), even with the changes above which help, `arrayDidChange` is still running too many times (around square times the number of items). Adding an `Ember.run.once` condition to launch the forEach loop solves the redundancies, I hope it is alright to use `run.once` here.

**Comment by stefanpenner** [comment]
@Leooo sorry, i haven't looked at this code in ages.

New array computed (in ember 2.0 beta) wont have this problem, as its all lazy and well behaved.

**Comment by Leooo** [comment]
OK forget my second point above then, the first point, your initial comment for your code was:
"// ignore if all changes are out of the visible change"

And this is how I understand it: check that the changes are in the visible range. In that case, this should be "&&" not "||".

Leaving the issue closed it works on my side now.

**Comment by stefanpenner** [comment]
> And this is how I understand it: check that the changes are in the visible range. In that case, this should be "&&" not "||".

if you can provide a failing test or something, i would love to be confident in the change. Unfortunately i don't have the extra cycles right now to validate your finding myself.

**Comment by Leooo** [comment]
Fair enough, not able to provide a test given my Ember level so forget it.

**Comment by stefanpenner** [comment]
> Fair enough, not able to provide a test given my Ember level so forget it.

we need more hours in the day :(
