### ISSUE TITLE
docs should be without globals as they are deprecated.

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/list-view#163]

**Comment by SebastianSzturo** [comment]
Could someone explain how to use list-view in ember-cli right now?

**Comment by stefanpenner** [comment]
@sebastianseilund i'll try to actually addonize it this weekend. It has been extremely overdue.

**Comment by Genkilabs** [comment]
Thank you @stefanpenner. The CLI seems to be becoming the norm so making list-view integrate smoothly is greatly appreciated.

**Comment by tim-evans** [comment]
This is a duplicate of #153.

**Comment by mrinterweb** [comment]
Issue #153 is closed, and the documentation still references globals. I am currently trying to figure out how to fix the deprecation warnings being thrown by the use of globals. So far, I have not had any luck. I'll just live with the deprecation warnings for now.

**Comment by tim-evans** [comment]
Mr. @samselikoff is working on the documentation ticket for this. If you'd like a separate ticket for deprecation warnings, we'd definitely welcome that!

**Comment by samselikoff** [comment]
yes now that #203 is merged I'm going to go back through and update (after this week's conference)
