### ISSUE TITLE
Absolute positioned children can get cut off

### ISSUE THREAD

**Issue by raytiley** [emberjs/list-view#164]
This issue is more to make others aware and solicit feedback if I should add this to the docs for list-view. The problem is if you have absolute positioned children in your list-view rows that flow overflow the row it will be cut off by the parent rows siblings. I've created a simple jsbin that demonstrates this and a fix outside of ember / list-view.

http://jsbin.com/makok/1/

This can happen if  your trying to use a component like ic-autcomplete or something similar inside a list-view-item. The fix I came up with is to increase the z-index of the parent so it is higher than its siblings. The jsbin above shows it.

My CSS isn't the strongest, so if there is a more elegant solution to this problem, I would love to see it.

**Comment by stefanpenner** [comment]
i wonder if we should add the concept of _focusing a row_
