### ISSUE TITLE
When scrolling list-view automatically selects/ the first item 

### ISSUE THREAD

**Issue by samratjp** [emberjs/list-view#166]
Hi there! 

This is my first item using list-view and am super happy how much this has reduced my page rendering times!! Currently, the biggest issue I have with it is whenever I scroll - the list view selects/clicks on the first item in the next virtual page of items. 

This is my current list-view setup (in emblem). The one way I've prevented this from happening is killing the link-to line (link-to 'participant' this currentWhen='participant'). Any suggestions/thoughts?

```
.list.mid-column-inner.candidates.candidates-show-sidebar
  .list.mid-column-inner
    collection Ember.ListView contentBinding="arrangedContent" height=1200 rowHeight=50 width=500
      %div class=isHidden:hide:show
        link-to 'participant' this currentWhen='participant'
          .applicant class=read:read-applicant:unread-applicant
            .applicant_portfolio
              .image-wrapper style=background_portfolio_url
            %ul.text
              %li
                %strong
                  first_name
                  '
                  last_name
```

Thanks!

I'm using:

ember-data-source (1.0.0.beta.6)
ember-rails (0.14.1)
ember-source (1.4.0.beta.4)
      handlebars-source (~> 1.3.0)
emblem-source (0.3.11)

And 278bd97 version of ember-list-view

**Comment by SebastianSzturo** [comment]
Another fix for that is to use link-to with ```this.id```

```
{{#link-to "item" this.id}}
  {{list-view-item item=this}}
{{/link-to}}
```

**Comment by stefanpenner** [comment]
@sebastianseilund yes that is required for, do to how link-to "binds" to data, and how reusable list item view does its thing. I am pretty excited for the new HTMLBars + view layer work happening in ember, as those features will ultimately prevent us from needing the ReusableListItemView instead the ListItemView will be sufficient, and many bugs (hopfully) like this one, will go away.

**Comment by Josh-Mosh** [comment]
Has anyone found a fix for this issue involving select elements?  When scrolling out of view, the first option is automatically selected.  We're already using `ListItemView` over `ReusableListItemView` so far as I can tell.  I can provide project context if it would be helpful.
