### ISSUE TITLE
virtual-list-view links do not work on iOS / Safari Mobile

### ISSUE THREAD

**Issue by Genkilabs** [emberjs/list-view#170]
You can see this easily by running an in-browser iOS emulator (I used chrome) and navigating to the list-view demo page, then changing one of the Virtual List View items to a link and trying to click it.
Here is a screenshot http://screencast.com/t/xSfKXJ2E0Ll9

I believe this might be a bug in the Zynga Scroller, perhaps related to https://github.com/zynga/scroller/issues/40

I'm really just documenting it here for others looking for info on the issue, and to perhaps open up discussion of workarounds or other scroller options. Any thoughts?

**Comment by fivetanley** [comment]
@Genkilabs any luck?

**Comment by Genkilabs** [comment]
Nope, I ended up giving up on the list-view projects and rendering full lists then wrapping them in https://github.com/eviltrout/ember-cloaking

This seems to perform even better on desktop, and also works on iOS through ember-cli-cordova
