### ISSUE TITLE
virtual list view + Yosemite  scrolls the wrong way

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/list-view#176]

**Comment by jayphelps** [comment]
Which browser and scroll direction setting? I'm on OS X 10.10.1, Chrome, both natural/historic scrolling settings = works as expected.

I'm guessing this is happening in a browser that doesn't support [event.webkitDirectionInvertedFromDevice](https://github.com/emberjs/list-view/blob/2270c05493055d9db83119fab69aae288c3a8827/packages/list-view/lib/virtual_list_view.js#L185), but this may no longer be an issue (Chrome or what ever browser you were using may have added it)

**Comment by stefanpenner** [comment]
@jasonmit fixed this, thanks for reminding me of this :)
