### ISSUE TITLE
List items overlap when scrolling

### ISSUE THREAD

**Issue by mkolenda** [emberjs/list-view#178]
Ember: 1.7
list-view: // Last commit: 278bd97 (2014-08-03 23:35:17 -0400)
Handlebars:  1.1.2
jQuery: 1.10.2
Gist with issue: https://gist.github.com/mkolenda/ea65e93db85bf912d839
Screenshot of issue: https://www.dropbox.com/s/7zijw9v0bvrj6j4/Screen%20Shot%202014-12-09%20at%203.47.58%20PM.png?dl=0

Steps
Run the app in the Gist
Scroll down the list
Notice elements render on top of each other

What have I done wrong?

**Comment by bargar** [comment]
Thanks, @mkolenda - you saved me some time by pointing this out!

**Comment by oskarrough** [comment]
Another case of RTFM: be sure to define rowHeight on the component to match the exact height of your items.
