### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/list-view#180]
maybe 0.1.0 for master (this weekend)
and 0.2.0 for pack when it lands

Maybe consider 1.0 as the last release for the 1.x branch of ember and the 2.0 aligned with 2.0 release after which i would like to try and keep releases here in lock step with ember.

cc @rwjblue @jasonmit

**Comment by kenips** [comment]
@stefanpenner what are the steps remaining to get http://builds.emberjs.com/list-view/list-view-latest.js updated? Need help?

**Comment by stefanpenner** [comment]
@kenips would love help, @fivetanley and @rwjblue are more familiar with that part of our deployment process.

**Comment by kenips** [comment]
ping @rwjblue - sorry know you're super busy but if you can take a look - desperately need `builds.emberjs.com` to have the 1.9 goodies.

**Comment by fivetanley** [comment]
@kenips Sorry for the delay, I will catch up this weekend. For now the README has been replaced to use https://rawgit.com/rondale-sc/list-view-dist/canary/list-view.js as the download link. You can put that in bower as well.

**Comment by kenips** [comment]
Thanks @fivetanley! Yeah I've been using custom dist for awhile now. Just trying to send PRs to some repos that rely on `builds.emberjs.com` so will wait for that to update :). Thanks so much!
