### ISSUE TITLE
Multi-height rows affecting display of other rows when off-screen

### ISSUE THREAD

**Issue by imkmf** [emberjs/list-view#186]
I have an instance of ListView with dynamic `rowHeight` – talked about it in a [previous issue](https://github.com/emberjs/list-view/pull/177#issuecomment-66544964). 

**tl;dr - Two 'expanded' rows with heights of 200px in the midst of 'non-expanded' 100px rows cause display errors as you scroll down the list.**

A bit of context (and a JSbin): 

We have an instance of ListView. When a row is clicked, an attribute on that object is updated, which in turn updates a `rowHeight` property that ListView updates the view with (using `_rowHeightDidChange`). **This part works great.** Our issues began when we recently added support for expanding "related" rows at the same time as the clicked row, which is causing some interesting display issues. For instance, a row that has a "parent" id two items down will expand when that "parent" row is clicked.

This is a bit nebulous so I've made a pretty simple [JSbin](http://jsbin.com/tewedu/1/) to simulate it as best I can. Note that the "related" functionality is bad in the example – it finds the object with half the index of the selected row and expands it as well. Mostly wanted something to use as an example. 

![screen shot 2015-01-07 at 10 37 03 am](https://cloud.githubusercontent.com/assets/922353/5651075/28ff7172-9659-11e4-8a99-ca3ef30082e6.png)

> Expanded items at the beginning of the list 

![screen shot 2015-01-07 at 10 36 25 am](https://cloud.githubusercontent.com/assets/922353/5651080/335ae1f6-9659-11e4-8b87-10a993795e44.png)

> Display error further down list. Notice extra space between previous row and bottom of scroll frame

The DOM structure and `ReusableListItemView` objects don't reveal anything particularly unusual. The `rowHeight` for each is as expected: `100` for non-expanded, `200` for expanded. The "item 8" in the above screenshot has the highest Y-value in `transform: translate(x, y)` (it's the last item in the `.ember-list-container` DOM structure as expected). 

Kinda hoping that I might just be doing something wrong, because this is kind of an outlier use-case and I'd rather it not muck up the current ListView implementation, which we've had a lot of success with so far. Let me know if there's more info I can provide. Thanks!

**Comment by imkmf** [comment]
Ah, I forgot to mention that the JSBin is using a version of ListView built the week of 12/1/14 so if this is something that's been fixed since then, my bad!

**Comment by imkmf** [comment]
Damn, I'm actually seeing now in my app that even a single expanded row can cause similar display issues. I can't recreate it in the JSBin (only with multiple expanded rows) so I'm hoping that if we find a fix to this it'll solve both situations.

**Comment by stefanpenner** [comment]
I suspect this is fixed in the pack branch. I promise to find time soon to get that branch in sync in master..

**Comment by imkmf** [comment]
Ah, curious what makes you suspect that? Trying to determine if there's an alternate approach I should be taking (as in, am I doing this wrong?) or if it's just worth it to wait for the new branch to make it to master...

**Comment by imkmf** [comment]
@stefanpenner sorry to be *that* guy, but any update on this? Alternatively, would you consider the pack branch safe for us to merge locally on our list-view.js for the sake of getting this fixed temporarily?

**Comment by tim-evans** [comment]
@imkmf @stefanpenner is working on the pack branch- he's stuck on a bug here in the pack code: https://github.com/stefanpenner/pack/blob/master/index.js#L259-L282

Any help would be very welcome :)

**Comment by imkmf** [comment]
@tim-evans, @stefanpenner we've since moved to a different lib :( sorry I can't be much help on this

**Comment by tim-evans** [comment]
No problem! Could you let us know which library you moved to? It'd be good to see where people are landing.

Cheers!

**Comment by imkmf** [comment]
We went with [ember-cloaking](https://github.com/eviltrout/ember-cloaking/). Was pretty easy to transition between the two.

**Comment by tim-evans** [comment]
That seems like the best choice for variable height rows at the moment :)

I'll close this issue as you're no longer tracking it.
