### ISSUE TITLE
continue addonization

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/list-view#193]
this is a tracking issue for when someone has time.

- [ ] ship the ES6 code
- [ ] move to conventional file structure
```
app/*
addon/*
```

- [ ] emit a legacy build

cc @taras @fivetanley @jasonmit

**Comment by jasonmit** [comment]
> emit a legacy build

Worth mentioning, since I just did this, that liquid-fire has a custom build pipeline for addons to build for legacy. https://github.com/ef4/liquid-fire/tree/master/packaging

Could be a good resource for whoever takes this up

**Comment by stefanpenner** [comment]
@jasonmit thanks :) Maybe we can pair on this soon!
