### ISSUE TITLE
Need to build assets after install

### ISSUE THREAD

**Issue by taras** [emberjs/list-view#195]
#192 that was merged earlier today needs a small tweak. We need to build assets after `npm install` so it will have an AMD build to use. If we added `ember build --environment=production` it should do the trick.

Can we add it to `postinstall` hook? like this

```
  "scripts": {
    "start": "ember server",
    "postinstall": "bower install && ember build --environment production",
    "demo": "ember build && node lib/demo_server.js",
    "docs": "./bin/generate_docs.js",
    "test": "ember test",
    "build-all": "ember build --environment production"
  },
```

If this is ok, then I'll make a PR.

**Comment by rwjblue** [comment]
It need to be packaged and pushed to NPM with the built assets, not force them to be built by every consumer.  That would be the `prepublish` hook...

**Comment by taras** [comment]
Like this? 
```
"scripts": {
    "start": "ember server",
    "postinstall": "bower install",
    "demo": "ember build && node lib/demo_server.js",
    "docs": "./bin/generate_docs.js",
    "test": "ember test",
    "build-all": "ember build --environment production",
    "prepublish": "ember build --environment production"
  },
```

Are we ok with including the built assets in the library?

**Comment by rwjblue** [comment]
It will need to be included when we publish to NPM, not stored in the repo.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/list-view/issues/193 solves the problem entirely, without needing the intermediate build step

**Comment by taras** [comment]
Ok, I'll leave it then. I just wanted to bring it your attention because the library is still not usable as an ember-cli addon in it's current state.

**Comment by taras** [comment]
@tim-evans I think we can close this issue.

**Comment by tim-evans** [comment]
:+1:  #193 seems like the right place to do this work
