### ISSUE TITLE
Add installation instructions for ember-cli > 0.44

### ISSUE THREAD

**Issue by flyswatter** [emberjs/list-view#198]
The current instructions are for <= 0.44, but ember-cli has changed since then, so I assume there's a new series of steps to use this.  But what are they??

**Comment by tim-evans** [comment]
list-view currently doesn't work as an ember-cli addon, but it will in the near(ish) future. For now, please use the download as a file under `vendor` in your ember-cli app and import it by calling:

```javascript
app.import('vendor/list-view.js');
```

Documentation and installation instructions will be updated when the 0.1.0 milestone is complete.

**Comment by tim-evans** [comment]
You also may have to build the repo by following the instructions in the README.

**Comment by flyswatter** [comment]
Oh also looks like @mysterlune [made this an addon already](https://www.npmjs.com/package/ember-cli-list-view).

**Comment by tim-evans** [comment]
Yep! Keep in mind that that will be deprecated in favor of the canonical ember-list-view addon that will be published as part of the 0.1.0 milestone.

**Comment by mysterlune** [comment]
@tim-evans, @flyswatter, indeed. the build i published was a stop-gap for those of us who want to just bang out projects with the addon style implementation. watching the list-view repo (and the issue https://github.com/emberjs/list-view/issues/160) for my cue to pull my repo down.

not much will change for consumers; just need to make sure list-view@0.1.0 hits this todo so i can deprecate.

**Comment by tim-evans** [comment]
Thanks, @mysterlune - I'll be sure that this gets done when 0.1.0 hits :)
