### ISSUE TITLE
Helpers are broken with Ember 1.10.0 with HTMLBars

### ISSUE THREAD

**Issue by sly7-7** [emberjs/list-view#199]
Since https://github.com/emberjs/ember.js/commit/ad62ccfdfd9578884261c96a2af4a6a238bd3ae9, HTMLBars.registerHelper is private. This broke the helpers here: https://github.com/emberjs/list-view/blob/master/packages/list-view/lib/main.js#L14
Could we use the private method, or use the public makeBoud/ViewHelper method ?

Also unless I'm missing something Ember.HTMLBars.helpers does not exists. https://github.com/emberjs/list-view/blob/master/packages/list-view/lib/helper.js#L22

**Comment by rwjblue** [comment]
> Could we use the private method, or use the public makeBoud/ViewHelper method ?

Yes, the simplest work around for now would be to use `Ember.HTMLBars._registerHelper`.

> Also unless I'm missing something Ember.HTMLBars.helpers does not exists.

You are not mistaken, there is no `Ember.HTMLBars.helpers` API.  You can use the older `Ember.Handlebars.helpers` API if you need it..

**Comment by tim-evans** [comment]
@sly7-7 I believe this is fixed by the recent merge by @taras.

**Comment by sly7-7** [comment]
@tim-evans Thank you for the reminder. I closed my related PR, but I forgot to close this one.

**Comment by tim-evans** [comment]
Thanks :heart:
