### ISSUE TITLE
Add block params to {{ember-list}} helper

### ISSUE THREAD

**Issue by tim-evans** [emberjs/list-view#202]
I would like to use block params for list-view just like the each helper:

``` handlebars
{{#ember-list items=items as |item index|}}
  {{index}}. {{item.name}}
{{/ember-list}}
```

Feedback on restrictions this causes on users would be great :)

**Comment by stefanpenner** [comment]
interesting

**Comment by oskarrough** [comment]
Is this what is needed before this will work? Need to pass a property from my controller down to the component. Or am I missing something super basic about contexts here?

```JavaScript
{{#ember-list items=model height=500 rowHeight=40}}
  {{track-item track=content fish=controller.something}}
{{/ember-list}}
```

**Comment by tim-evans** [comment]
@oskarrough The template you provided is a good interim step for refactoring.

Your template would change to:
```handlebars
{{#ember-list items=model height=500 rowHeight=40 as |track index|}}
  {{track-item track=track fish=controller.something}}
{{/ember-list}}
```

**Comment by oskarrough** [comment]
@tim-evans exactly. But it doesn't work yet. Correct?

**Comment by tim-evans** [comment]
Correct. This isn't implemented yet.

**Comment by krisselden** [comment]
@tim-evans this will be how it has to work for ember 2, I'm planning on moving it away from item views.

**Comment by tim-evans** [comment]
@krisselden super!

**Comment by ahmed1490** [comment]
Hi any update here?

**Comment by raytiley** [comment]
There is some initial spikes how of how list-view will work in glimmer. https://github.com/krisselden/list-view/tree/2.0.0. 

You can see how the new syntax looks here: https://github.com/krisselden/list-view/blob/2.0.0/tests/dummy/app/templates/simple.hbs#L18-L22
