### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by andreyfel** [emberjs/list-view#205]
"npm run build-all" became invalid after the #203 PR was merged.

**Comment by jasonmit** [comment]
Intentional as we moved this to an ember-cli addon.  

There may be work to create a custom build pipeline to support globals for backwards compat.

Cc @stefanpenner To hear his thoughts

**Comment by stefanpenner** [comment]
I have very little  motivation to support globals, but if that is a popular request we can easily support it, but wrapping the output with it's own local loader and re-exporting the things we need for globals.

**Comment by jasonmit** [comment]
Err, sorry.  

I think we spoke about bringing over something comparable to what liquid fire does to handle custom builds.  It doesn't involve globals :)

**Comment by stefanpenner** [comment]
> I think we spoke about bringing over something comparable to what liquid fire does to handle custom builds. It doesn't involve globals :)

ah ok
