### ISSUE TITLE
Publish NPM module / Ember Addon

### ISSUE THREAD

**Issue by taras** [emberjs/list-view#212]
@stefanpenner and I were discussing releasing a beta version of this library. A few things came up, I wanted to highlight in preparation for that release.

@ebryn suggested that we call it `ember-list-view` until Ember 2.0 (and we come up with a better name). 

We'll also need to change the module name, so I'll need to do some refactoring to the library to use the new name.

//cc @tim-evans

**Comment by stefanpenner** [comment]
> @ebryn suggested that we call it ember-list-view

:+1:

**Comment by tim-evans** [comment]
Closing this because of #225 being merged. :+1:
