### ISSUE TITLE
Docs incorrect?

### ISSUE THREAD

**Issue by alexspeller** [emberjs/list-view#214]
http://emberjs.com/list-views suggests this doesn't work on iOS but it seems to work fine - are the docs outdated?

**Comment by stefanpenner** [comment]
it works as of iOS 8 they now report the scroll events even during momentum phase, which means you don't need to use the virtualListView on the newest iOS's

**Comment by alexspeller** [comment]
Would you like a docs PR?

**Comment by stefanpenner** [comment]
yes please

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...
