### ISSUE TITLE
Demo site breaks in IE8

### ISSUE THREAD

**Issue by xrl** [emberjs/list-view#220]
Is list-view targeting support for IE8? I am trying to get the addepar ember-widgets select-input component to work on my site but it looks like list-view is breaking even booting the app. This has me trying to isolate the breakage and I can see that the list-view demo site does not render properly in IE8. Is the demo site expected to work?

![screen shot 2015-03-26 at 12 36 26 pm](https://cloud.githubusercontent.com/assets/693059/6855389/f837884c-d3b4-11e4-9488-c259652a190b.png)

**Comment by stefanpenner** [comment]
It is currently not targeting ie8.
