### ISSUE TITLE
How to add a class to a list item element

### ISSUE THREAD

**Issue by marcemira** [emberjs/list-view#228]
I need to add a class (i.e. 'myClass') to the list item at current 0.6 :

``` handlebars
{{#ember-list height=100  items=model.items width=100 rowHeight=20}}
  Hello
{{/ember-list}}
```

and produce (notice the 'myClass' in the list-item):

``` html
<div id="ember890" class="ember-view ember-list-view ember-list-view-list" style="height:559px;position:relative;overflow:auto;-webkit-overflow-scrolling:touch;overflow-scrolling:touch;">
  <div class="ember-list-container" style="height: 2020px;">
    <div id="ember895" class="ember-view ember-list-item-view myClass" style="transform: translate(0px, 600px)"> Hello </div>
  </div>
</div>
```

How can I achieve this? Thanks!

**Comment by stefanpenner** [comment]
you must add an addition element within the row to bind to classes.

**Comment by stefanpenner** [comment]
we may open up support to the inner row in the future, but at the time, due to an issue in ember we could enable this.

**Comment by marcemira** [comment]
:+1:  Thanks Stef

**Comment by stefanpenner** [comment]
likely something we need to address in the docs.

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...
