### ISSUE TITLE
Scrolling list-view fast causes page to scroll

### ISSUE THREAD

**Issue by jacojoubert** [emberjs/list-view#229]
If you flick your mouse to scroll it will scroll through the list, hit the bottom and then scroll the page. After the scroll momentum is gone you can resume scrolling list-view.

![animation](https://cloud.githubusercontent.com/assets/41799/7024735/e2787a78-dd0c-11e4-9233-7580242d9e3a.gif)

**Comment by tim-evans** [comment]
I think this has to deal with list-view not processing view recycling fast enough for the browser.

**Comment by jacojoubert** [comment]
This was my fault. I guess something changed in how scrolling is handled in the newest list-view and it invalidated my previous code. Sorry to have wasted your time.
