### ISSUE TITLE
Latest development download broken (?)

### ISSUE THREAD

**Issue by jonnii** [emberjs/list-view#231]
the link to the build output in the readme is still pointing to 0.5.0 which makes me think that part of the build might be broken?

https://rawgit.com/rondale-sc/list-view-dist/canary/list-view.js

we are trying to upgrade to 1.11.1 and aren't (yet) on ember-cli so we can't use the add-on =(

**Comment by tim-evans** [comment]
Try https://github.com/ef4/ember-giftwrap :)

**Comment by jonnii** [comment]
Is there anything I can do to help with this? Does the build no longer produce a globals version of list-view?

**Comment by taras** [comment]
It doesn't at the moment, but a PR would be welcomed :)

**Comment by jonnii** [comment]
Can you point me in the direction of where to start? I have some time I can take a look.

**Comment by taras** [comment]
@ef4 @stefanpenner do you guys have any direction on how we should provide a globalized build for this addon?

**Comment by jonnii** [comment]
@taras I'm assuming this problem is solver in ember itself, I'm going to poke around and see what I can find. There might be other add-ons that have had to solve this, probably something like ember-validations.

**Comment by ef4** [comment]
It should be possible to produce a globals-compatible build using http://github.com/ef4/ember-giftwrap

**Comment by jonnii** [comment]
@ef4 i'll try giftwrap on monday...

**Comment by catc** [comment]
@jonnii any luck with giftwrap?

**Comment by jonnii** [comment]
@catc not yet, I'm spending Friday's upgrading ember, so will give it a try in a couple of days. Right now we're trying to upgrade from 1.8 => 1.10 (this is the last version of list-view which has globals), but there's a bug with 1.10 which results in our modals not working (something to do with controller bindings in views without outlets according to the changelog), so we might have to skip to 1.11. Will revert with full trip report.

**Comment by jonnii** [comment]
@ef4 @catc finally got around to trying giftwrap and everything has seemed to work. A few things like having to remove the ember-data and ic-ajax packages from ember-cli's default output should be documented, plus it's a little out of date in terms of `ember install:addon` vs `ember install`. but other than that so far so good.

**Comment by severinedarlot** [comment]
Hello, we have the same problem than @jonnii . We don't use ember-cli. We use gem ember-rails. Usually we use the link 'latest development' in the readme but now it is not up-to-date.

I try to create a globalized build with giftwrap but I failed. Here is what I did :

    ember new list-view
    # edit the package.json file to remove "ember-cli-sri": "^1.0.1", "ember-cli-ic-ajax": "0.2.1", "ember-data": "1.13.7",
    npm rm ember-data --save-dev  
    npm rm ember-cli-ic-ajax --save-dev
    npm rm ember-cli-sri --save-dev
    npm install
    bower install
    ember install ember-list-view
    ember install ember-giftwrap
    ember giftwrap

I obtain a file addon.js and I put its content in our application

Next, I added after our app creation:

    GiftWrap.install(App)

But when I run our application, on the line ````App.MyListView = Ember.ListView.extend({..```` I obtain the error:

    Uncaught TypeError: Cannot read property 'extend' of undefined

I try to add

    Ember.ListView = GiftWrap.require('ember-list-view')

But it didn't help me. I guess I should use GiftWraph in a particular manner but I don't find how. @ef4 @catc have you got an idea to help me ? We just want to use the last version of list-view.

Thanks

**Comment by jonnii** [comment]
`EmberListView = GiftWrap.require('ember-list-view').default`. 

try that.

**Comment by severinedarlot** [comment]
Wonderful, it works ! I had:

    Ember.ListView = GiftWrap.require('ember-list-view').default;
    Ember.ListItemView = GiftWrap.require('ember-list-view/list-item-view').default;

Thank you very much.

**Comment by jonnii** [comment]
no problem, took me a while to work that one out... :dancer:

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...
