### ISSUE TITLE
Incorrect number of elements shown when element exceeds container height

### ISSUE THREAD

**Issue by Geokoumpa** [emberjs/list-view#238]
Hello,

I have implemented a multi-level nested tree of collapsible elements, by taking advantage of

```
heightForIndex
```

and

```
updateRows
```

Everything seemed to work as expected, until some of my data branches had a big number of descendants, such that the total height of the root element was greater than that of the container. 

![](https://lh4.googleusercontent.com/-7pqI1LwMoy0/VTQQ1M9SMzI/AAAAAAAAD_w/f3mWToyEmYg/w722-h683-no/t.png)
As I start scrolling, at some point, it stops functioning properly, as it shows less items than needed to fill the container area. I have verified that heightForIndex is calculated correctly and accurately. The calculation is done via 

```
  heightForIndex: (idx)->
    entry = @get('content').objectAt(idx)
    if entry.get('collapsed')
      return @rowHeight * entry.get('selfAndDescendantsRows')
    else
      @rowHeight
```

where selfAndDescendatsRows is a computed property inside the model that populates the tree / list.

This is very disappointing because other than this issue, the whole system works impressively well, so any help would be much appreciated. 

thanks!

**Comment by stefanpenner** [comment]
> This is very disappointing because other than this issue,

ya it's a bummer, we will need to fix this. But a good scenario :)

**Comment by tp** [comment]
For a tree-view like structure I built a component (in-house), that has no nested list views, but rather just indents items based on their depth in a single list view.

The code slightly more complicated than the straightforward way, but uses much less elements than other approaches and is always fast, no matter how many nodes are open/visible.

Maybe that would work for you as well.

**Comment by Geokoumpa** [comment]
I would gladly try your component as well tp, thanks!

**Comment by tim-evans** [comment]
This will probably be fixed on the pack branch.

**Comment by stefanpenner** [comment]
> This will probably be fixed on the pack branch.

maybe, im unsure about this specific use-case though.

**Comment by scooterlord** [comment]
Hello. Any news on this one? Haivng the same issue and would be glad to have this solved!

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...
