### ISSUE TITLE
Add Binding-in, Action-out, Scroll Position

### ISSUE THREAD

**Issue by jeff3dx** [emberjs/list-view#251]
I'd like to see this emit a **scroll action**, and the ability to **push scroll position** in from an external source, preferably as a percentage rather than the absolute scrollTop.  (Is it possible to implement list-view as a Component?)

**The in-property:**
- scrollPositionPercentage

**The out-action should include at least:**
- height
- totalHeight
- scrollTop

The use case is to render a scroll helper on my UI that follows that scroll position of the list. The helper UI needs to know position and how much of the total list is actually visible, as a percentage.  All can be calculated from the above three values.

(list-view works nicely as is.  However my attempts to subclass or event fork it had strange results just by adding a bit of code to produce the actions.  Apparently this thing is a delicate balance easily broken without more study.)

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is essentially unmaintained.  Please use @html-next/vertical-collection or ember-collection for similar functionality.

Closing...
